server:
  port: 8088
  servlet:
    context-path: /idem/api/

spring:
  application:
    name: idem-tech-mate-example
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 30000
    lettuce:
      pool:
        # 连接池最大连接数，若为负数则表示没有任何限制
        max-active: 50
        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
      shutdown-timeout: 1000

idem:
  limiter:
    uri-config:
      test:
        count: 10
        requestDuration: 1
        limitDuration: 10
        bucketKey:
          - /idem/api/test/query
          - /idem/api/test/tech
